server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true #SQL문을 print로 출력
        format_sql: true #SQL 문을 보기좋게 출력
  application:
    name: graphQL-Test
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:

logging:
  level:
    com.example.graphql: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace

graphql:
  servlet:
    enabled: true
    mapping: /graphql
    corsEnabled: false
    cors:
      allowed-origins: http://localhost:8080
      allowed-methods: GET, POST, PUT, DELETE, HEAD, PATCH
    exception-handlers-enabled: true
    context-setting: PER_REQUEST_WITH_INSTRUMENTATION
  tools:
    schema-location-pattern: "graphql/*.graphqls"
    introspection-enabled: true
